version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for cargo updates at 3am UTC
      time: "03:00"
    open-pull-requests-limit: 10
    groups:
      batch:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for cargo updates at 3am UTC
      time: "03:00"
    open-pull-requests-limit: 3
